server:
  port: 8080

spring:
  web:
    resources:
      static-locations: /WEB-INF/views/, classpath:/static/
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/product-management
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 70MB

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog.yaml
    default-schema: public

jwt:
  secret: "secure_secret_key"
  expiration: 3600000

logging:
  level:
    root: INFO  # общий уровень логирования (DEBUG, INFO, WARN, ERROR)
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.SQL: DEBUG  # логи SQL-запросов
  file:
    name: logs/app.log  # Логи будут сохраняться в logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"  # формат для консоли
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # формат для файла

